#!/bin/bash

riscv64-linux-gnu-as -o firefly-lantern-linux.o firefly-lantern-linux.s -march=rv32im
riscv64-linux-gnu-ld -T mecrisp.ld -z max-page-size=4096 -o firefly-lantern-linux firefly-lantern-linux.o -m elf32lriscv
riscv64-linux-gnu-objdump -Mnumeric -D firefly-lantern-linux > firefly-lantern-linux.list

rm -f firefly-lantern-linux.o
